# -*- coding: utf-8 -*-
"""speech-to-text_using_open-ai_whisper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vSr45k6CS37ijH6VTc92wOKAeBagdkIl

# Speech-to-text using openai whisper

GPU Check
"""

!nvidia-smi

"""Installation"""

! pip install git+https://github.com/openai/whisper.git -q

"""Load the Library * Model"""

import whisper

model = whisper.load_model("medium")

!wget -O audio.mp3 http://www.moviesoundclips.net/movies1/batmanbegins/bats.mp3

from IPython.display import Audio, display

display(Audio('audio.mp3', autoplay=True))

"""Speech to text transcription"""

result = model.transcribe("audio.mp3")
print(result["text"])

import whisper

tiny = whisper.load_model("tiny")

result = tiny.transcribe("audio.mp3")
print(result["text"])

"""Speech-to-text"""

import whisper
model = whisper.load_model('medium')
model.transcribe("audio.mp3")['text']